### ISSUE TITLE
Binary releases?

### ISSUE THREAD

**Issue by gd4c** [phiresky/tree-magic-cli#1]
Hi,

Could you please release builds, particularly for Windows?

Thanks

**Comment by phiresky** [comment]
I don't think I'm willing to spend the effort to setup CI, especially since building stuff for Windows is really annoying. If you have rust, `cargo install tree-magic-cli` should work right?

Also, this module is really more useful for debugging than general purpose, I'd usually just use `file`

PRs are welcome of course :)

**Comment by gd4c** [comment]
I see.
There is benefit to an "official" release, but I respect your decision.

 Thanks anyway.
